# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

project_name: stashcp

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    id: "stashcp"
    dir: ./cmd/stashcp
    binary: stashcp
    tags:
      - forceposix
    ignore:
      - goos: windows
        goarch: arm64
  - env:
      - CGO_ENABLED=0
    main: ./cmd/stash_plugin
    goos:
      - linux
      - windows
      - darwin
    id: "stash_plugin"
    binary: stash_plugin
    tags:
      - forceposix
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

nfpms:
  - package_name: stashcp
    builds:
      - stashcp
      - stash_plugin
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    id: stashcp
    vendor: Open Science Grid
    homepage: https://github.com/opensciencegrid/stashcp
    maintainer: Derek Weitzel <dweitzel@unl.edu>
    description: Client copy tool for the StashCache federation
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    replaces:
      - stashcache-client
    bindir: /usr/bin
    release: 1
    section: default
    priority: extra
    overrides:
      rpm:
        replacements:
          amd64: x86_64
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Release }}.{{ .Arch }}"
      deb:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Release }}_{{ .Arch }}"
