project_name: pelican

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "amd64"
      - "arm64"
      - "ppc64le"
    id: "pelican"
    dir: ./cmd
    binary: pelican
    tags:
      - forceposix
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: ppc64le

archives:
  - id: pelican
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

nfpms:
  - package_name: pelican
    builds:
      - pelican
    file_name_template: "{{ .ConventionalFileName }}"
    id: pelican
    vendor: OSG Consortium
    homepage: https://github.com/PelicanPlatform/pelican
    maintainer: Brian Bockelman <bbockelman@morgridge.org>
    description: Command-line copy tool for the Open Science Data Federation
    license: ASL 2.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    release: 1
    section: default
    priority: extra
    overrides:
      rpm:
        contents:
          - src: LICENSE
            dst: "/usr/share/doc/{{ .PackageName }}-{{ .Version }}/LICENSE.txt"
            file_info:
              mode: 0644
            type: doc
          - src: README.md
            dst: "/usr/share/doc/{{ .PackageName }}-{{ .Version }}/README.md"
            file_info:
              mode: 0644
            type: doc
      deb:
        contents:
          - src: LICENSE
            dst: "/usr/share/doc/{{ .PackageName }}/LICENSE.txt"
            file_info:
              mode: 0644
            type: doc
          - src: README.md
            dst: "/usr/share/doc/{{ .PackageName }}/README.md"
            file_info:
              mode: 0644
            type: doc
  # end package pelican

  - package_name: pelican-osdf-compat
    builds: []
    file_name_template: "{{ .ConventionalFileName }}"
    id: pelican-osdf-compat
    vendor: OSG Consortium
    homepage: https://github.com/PelicanPlatform/pelican
    maintainer: Brian Bockelman <bbockelman@morgridge.org>
    description: OSDF compatibility files for Pelican
    license: ASL 2.0
    meta: true
    formats:
      - apk
      - deb
      - rpm
    # bindir: /usr/bin
    release: 1
    section: default
    priority: extra
    dependencies:
      - pelican
    provides:
      ## does not work: {{ .Version }} doesn't get substituted in this list
      # - osdf-client = {{ .Version }}
      # - stashcp = {{ .Version }}
      # - condor-stash-plugin = {{ .Version }}
      - "stashcache-client = 7"
      - "osdf-client = 7"
      - "stashcp = 7"
      - "condor-stash-plugin = 7"
    overrides:
      apk:
        contents:
          - src: "./pelican"
            dst: "/usr/bin/osdf"
            type: symlink
          - src: "./pelican"
            dst: "/usr/bin/stashcp"
            type: symlink
      rpm:
        contents:
          - src: "./pelican"
            dst: "/usr/bin/osdf"
            type: symlink
          - src: "./pelican"
            dst: "/usr/bin/stashcp"
            type: symlink
          - src: "../../bin/pelican"
            dst: "/usr/libexec/condor/stash_plugin"
            type: symlink
          - src: "client/resources/10-stash-plugin.conf"
            dst: "/etc/condor/config.d/10-stash-plugin.conf"
            type: config|noreplace
        replaces:
          - "stashcache-client < 7"
          - "osdf-client < 7"
          - "stashcp < 7"
          - "condor-stash-plugin < 7"
        ## rpm specific syntax:
        ## also does not work: %{version} doesn't get expanded
        # provides:
        #   - "osdf-client = %{version}"
        #   - "stashcp = %{version}"
        #   - "condor-stash-plugin = %{version}"
      deb:
        contents:
          - src: "./pelican"
            dst: "/usr/bin/osdf"
            type: symlink
          - src: "./pelican"
            dst: "/usr/bin/stashcp"
            type: symlink
          - src: "../../bin/pelican"
            dst: "/usr/libexec/condor/stash_plugin"
            type: symlink
          - src: "client/resources/10-stash-plugin.conf"
            dst: "/etc/condor/config.d/10-stash-plugin.conf"
            type: config|noreplace
        # deb has different syntax
        provides:
          - "stashcache-client (= 7)"
          - "osdf-client (= 7)"
          - "stashcp (= 7)"
          - "condor-stash-plugin (= 7)"
        replaces:
          - "stashcache-client (<< 7)"
          - "osdf-client (<< 7)"
          - "stashcp (<< 7)"
          - "condor-stash-plugin (<< 7)"
  # end package pelican-osdf-compet
