project_name: pelican

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "amd64"
      - "arm64"
      - "ppc64le"
    id: "pelican"
    dir: ./cmd
    binary: pelican
    tags:
      - forceposix
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: ppc64le
