# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: github_scripts/pelican_protocol.patch
    -   id: end-of-file-fixer
    -   id: check-yaml
        # Multi-documents are yaml files with multiple --- separating blocks, like
        # in our docs/parameters.yaml. We need this argument so those parse.
        args: [--allow-multiple-documents]
    -   id: check-added-large-files
        args: ['--maxkb=1024']
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
    -   id: golangci-lint
