# Toggle webhook to pull latest release onto pelicanplatform.org and update the download offerings there
name: post-release

on:
  release:
    types: [published]

jobs:
  toggle-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Toggle Webhook
        run: |
          curl -X POST https://dl.pelicanplatform.org/api/api/hooks/release-download-toggle
