name: Release, Build, and Push Dev Image

on:
  pull_request:
  push:
    tags:
      # only build and publish container on v7.0.0 and up
      - v[7-9]\.[0-9]+\.[0-9]+-**
      - v[1-9][0-9]+\.[0-9]+\.[0-9]+-**
    branches:
      - main

jobs:
  build-dev-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: hub.opensciencegrid.org/pelican_platform/pelican-dev
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest-itb
            type=ref,enable=true,prefix=itb-,suffix=-{{date 'YYYYMMDDHHmmss'}},event=tag
            type=raw,value=sha-{{sha}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to OSG Harbor
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.PELICAN_HARBOR_ROBOT_USER }}
          password: ${{ secrets.PELICAN_HARBOR_ROBOT_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: ./images/dev.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
